ShrtLnks/Controllers/LinkController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShrtLnks.Data;
using ShrtLnks.Models;
using ShrtLnks.ViewModels;

namespace ShrtLnks.Controllers
{
    public class LinkController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public LinkController(
            ApplicationDbContext context,
            UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }


        // GET: link
        public async Task<IActionResult> Dashboard()
        {
            string currentUserId = _userManager.GetUserId(User);

            var links = await _context.Link.Where(l => l.OwnerId == currentUserId).ToListAsync();

            DashboardViewModel dashboardViewModel = new DashboardViewModel()
            {
                Links = links
            };

            return View(dashboardViewModel);
        }

        // GET: link/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: link/Create
        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("longUrl")] string longUrl)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var currentUser = await _userManager.GetUserAsync(User);

            string shortUrl = "";
            while (shortUrl == "")
            {
                string testString = RandomStringGenerator();
                bool doesExist = await _context.Link.AnyAsync(l => l.ShortUrl == testString);

                if (!doesExist)
                    shortUrl = testString;
            }

            Link link = new Link()
            {
                OwnerId = (currentUser == null) ? "Anonymous" : currentUser.Id,
                LongUrl = longUrl,
                ShortUrl = shortUrl,
                CreateAt = DateTime.Now
            };

            _context.Add(link);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Details), new { id = link.LinkId } );
        }

        // GET: link/Edit/{id}
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var link = await _context.Link.FindAsync(id);
            if (link == null)
            {
                return NotFound();
            }

            var currentUser = await _userManager.GetUserAsync(User);

            LinkEditViewModel linkEditViewModel = new LinkEditViewModel()
            {
                Link = link
            };

            return View(linkEditViewModel);
        }

        // POST: link/Edit/{id}
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("LinkId,OwnerId,LongUrl,ShortUrl,CreateAt")] Link link)
        {
            if (!ModelState.IsValid)
            {
                return View(link);
            }

            if (link == null)
            {
                return NotFound();
            }

            try
            {
                _context.Update(link);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!LinkExists(link.LinkId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Dashboard));
        }

        // GET: link/delete/{id}
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var link = await _context.Link.FirstOrDefaultAsync(l => l.LinkId == id);
            if (link == null)
            {
                return NotFound();
            }

            return View(link);
        }

        // POST: link/delete/{id}
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var link = await _context.Link.FindAsync(id);
            _context.Link.Remove(link);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Dashboard));
        }

        //GET: links/details/{id}
        public async Task<IActionResult> Details(int id)
        {
            var link = await _context.Link.FindAsync(id);
            if (link == null)
            {
                return NotFound();
            }

            var currentUser = await _userManager.GetUserAsync(User);
            if (link.OwnerId != currentUser.Id)
            {
                return RedirectToAction(nameof(Dashboard));
            }

            return View(link);
        }

        private bool LinkExists(int id)
        {
            return _context.Link.Any(e => e.LinkId == id);
        }

        private static string RandomStringGenerator()
        {
            Random random = new Random();

            const string chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
            return new string(Enumerable.Repeat(chars, 7)
              .Select(s => s[random.Next(s.Length)]).ToArray());
        }
    }

}

ShrtLnks/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ShrtLnks</title>

    <environment include="Development">
        <link rel="stylesheet"
              href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
              crossorigin="anonymous" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet"
              href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
              crossorigin="anonymous" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
</head>
<body>
    <div class="nav-container">
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-dark indigo">
                <a class="navbar-brand" href="#">
                    <img class="navbar-logo"
                         src="~/images/shrtlnks_logo.svg"
                         alt="Short Links Logo" />
                </a>
                <button class="navbar-toggler"
                        type="button"
                        data-toggle="collapse"
                        data-target="#navbarText"
                        aria-controls="navbarText"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarText">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            @if (SignInManager.IsSignedIn(User))
                            {
                                <a class="btn my-nav-link" asp-area="" asp-controller="Link" asp-action="Dashboard">Dashboard</a>
                            }
                            else
                            {
                                <a class="btn my-nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            }
                        </li>
                        <li class="nav-item">
                            <a class="btn my-nav-link" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                    </ul>
                    <span>
                        <partial name="_LoginPartial" />
                    </span>
                </div>
            </nav>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - ShrtLnks</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
                integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
                crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
                integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
                crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
                integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
                crossorigin="anonymous"></script>
        <script src="~/js/site.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
                integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
                crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
                integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
                crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
                integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
                crossorigin="anonymous"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>